# Generated by Django 5.1.6 on 2025-02-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_todo_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
