# Generated by Django 5.1.6 on 2025-02-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_todo_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="is_complete",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
